src/locales/fr/translation.json, src/locales/index.ts, src/renderer/helpers.ts, src/renderer/hooks/use-download.ts
=> Added Translation Support to French

src/main/services/window-manager.ts
What kind of change does this PR introduce?
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Tests
[ ] Other
```
- Added a minWidth and minHeight to in window-manager.ts to prevent the application window from shrinking to the maximum
[Screencast from 2024-04-14 22-17-34.webm](https://github.com/hydralauncher/hydra/assets/82431727/b66253fe-7938-4185-8bb4-19928fdfe29a)
[Screencast from 2024-04-14 22-33-09.webm](https://github.com/hydralauncher/hydra/assets/82431727/28bf51d4-f983-463f-8e76-8cf2e2b9549d)
=> fix: add a minWidth and minHeight in app window

forge.config.ts, resources/hydra-launcher.desktop
- Change MakerRpm and MakerDeb functions to create a valid .desktop file
=> build: add linux .desktop entry

src/main/events/catalogue/get-catalogue.ts, src/main/services/steam-250.ts, yarn.lock
Removed unnecessary requests to algolia to get steam id and then get trending games, changed this to get steam id direct from steam250.
=> fix: remove algolia unnecessary requests

package.json, src/renderer/hooks/use-download.ts, src/renderer/pages/downloads/downloads.tsx, src/renderer/pages/game-details/hero-panel.tsx, src/renderer/pages/game-details/repacks-modal.tsx, src/renderer/utils/byteFormat.ts, src/renderer/utils/format-bytes.ts, src/renderer/utils/index.ts, yarn.lock
pretty bytes show KiB, MiB, GiB... format in base 2 values, it's correct but is usual to see the format in KB, MB, GB...
Brave
Edge
Windows
Github
=> refactor: remove pretty bytes

.github/workflows/build.yml, README.md, forge.config.ts, hydra-launcher.desktop, requirements.txt, torrent-client/setup.py
- Added `setup.py` cx_Freeze config file
- Change dependencies in `requirements.txt`
- Readded `forge` linux build config
- Readded linux `.desktop` file model
- Change build torrent client command in `README.md`
=> Build/change pyinstaller with cx_freeze

torrent-client/setup.py
- Add `icon` property in `Executable` object
=> build: add icon to client torrent exe

src/renderer/pages/game-details/game-details.css.ts
Fix for issue: https://github.com/hydralauncher/hydra/issues/68
=> 💄 fix game details description image size

src/locales/index.ts, src/locales/ru/translation.json
Added support for the Russian language.
=> added Russian language

package.json, src/main/events/torrenting/start-game-download.ts, src/main/services/download-manager.ts, src/main/services/downloaders/index.ts, src/main/services/downloaders/real-debrid.downloader.ts, src/main/services/real-debrid.ts, src/shared/index.ts, yarn.lock
- Changes the name of http downloader to real debrid, given that the class **only** supports real debrid and no other http source.
- Fixes the notification triggering before the download has been joined from parts into a single file.
- Unarchives the .rar file into the game files to the proper folder.
=> Improvements over the real debrid integration.

README.ru.md
Github won't let me add to the original README myself, so add the button yourself:
```
[![ru](https://img.shields.io/badge/lang-ru-red)](https://github.com/hydralauncher/hydra/blob/main/README.ru.md)
```
=> Translated README.md to ru

src/locales/ru/translation.json
Corrected some phrases that sounds artificial in Russian.
=> Update Russian translation

src/locales/ru/translation.json
Removed lots of unnecessary text
Polished everything for "euphony" of Russian
=> Improved RU translation

src/locales/ru/translation.json
Dunno how i oversaw it earlier, sorry
=> Fixed a typo in RU locale

package.json
=> change package name to hydralauncher

README.es.md, src/locales/es/translation.json
Added Splash Spanish translation
=> Updated Spanish translation

README.be.md, README.es.md, README.md, README.pl.md, README.pt-BR.md, README.ru.md, README.uk-UA.md
Added the button to redirect from the main readme in english (and other languages) to the spanish
Also, deleted the spanish button from the spanish readme (kinda confusing) and replaced with the english readme redirect button
=> Added a button to redirect to "README.es.md"

src/locales/it/translation.json
Fixed variable that should not be translated
=> Fixed incorrect translation of variable in italian translation

src/locales/es/translation.json
Bug fixed - ETA was bugged, making a word be repeated twice, changed to a different one to fix this
=> Fixed an error in Spanish translation

.gitignore, src/main/constants.ts, src/main/services/logger.ts
=> Change logs path to match hydra.db

src/locales/es/translation.json
Translated "version_available" string to spanish
=> New string added in Spanish translation

src/locales/es/translation.json
Using "**reiniciar**" (_restart_) instead of "**reinstalar**" (_reinstall_).
=> Typo correction

src/locales/es/translation.json
Translated new translations regarding Real-Debrid and some new strings
=> New translations added to Spanish

src/locales/es/translation.json
- Added new translations
- Deleted old ones to match english translation
=> New translation.json spanish

src/main/services/window-manager.ts
This fixes iframe not loading in linux
=> fix: set nodeIntegrationInSubFrames true on auth window

src/main/events/profile/get-me.ts, src/main/services/hydra-api.ts, src/renderer/src/context/game-details/game-details.context.tsx, src/renderer/src/declaration.d.ts, src/renderer/src/features/user-details-slice.ts, src/renderer/src/hooks/use-user-details.ts, src/renderer/src/pages/game-details/sidebar/sidebar.tsx, src/types/index.ts
- updates typing for getMe
- fixes repacks not loading when game details request fails
=> feat: update typing to match get me

.github/ISSUE_TEMPLATE/bug_report.yml, build/installer.nsh, src/main/services/hydra-api.ts, src/renderer/src/pages/game-details/gallery-slider/gallery-slider.css.ts, src/renderer/src/pages/game-details/gallery-slider/gallery-slider.tsx
=> fix: game details gallery align

src/locales/es/translation.json
- [ X ] I have read and understood the [Contributor Guidelines](https://github.com/hydralauncher/hydra?tab=readme-ov-file#ways-you-can-contribute).
- [ X ] I have checked that there are no duplicate pull requests related to this request.
- [ X ] I have considered, and confirm that this submission is valuable to others.
- [ X ] I accept that this submission may not be used and the pull request may be closed at the discretion of the maintainers.
- added missing strings
=> feature: updated spanish translation

docs/README.be.md, docs/README.da.md, docs/README.de.md, docs/README.nb.md
updating for the correct display of the icon and updating the site domain
=> Hydrasources patch 1 6

src/locales/ru/translation.json
adding a new phrase translation to russian
=> Update RU translation.json

docs/README.pt-BR.md
=> fix: update language anchor in README.pt-BR.md

src/renderer/src/pages/catalogue/catalogue.tsx
=> fix: adding debounce to search

src/main/services/download/download-manager.ts, src/renderer/src/helpers.ts, src/renderer/src/pages/profile/profile-content/profile-content.css.ts, src/renderer/src/pages/profile/profile-content/profile-content.tsx, src/renderer/src/pages/profile/profile-content/user-library-game-card.tsx
https://github.com/user-attachments/assets/9cd0d671-4bfa-4f89-abab-6f1e6a80be14
=> feat: game card stats animation

src/locales/bg/translation.json
- [ x] I have read and understood the [Contributor Guidelines](https://github.com/hydralauncher/hydra?tab=readme-ov-file#ways-you-can-contribute).
- [x ] I have checked that there are no duplicate pull requests related to this request.
- [x ] I have considered, and confirm that this submission is valuable to others.
- [x ] I accept that this submission may not be used and the pull request may be closed at the discretion of the maintainers.
PR:[translation]
-
=> PR:[translation] Bulgarian langguage add missing strings

src/locales/es/translation.json
=> updated spanish translation.json

src/main/services/hosters/mediafire.ts
=> Fix: Fix Mediafire hoster 403

src/locales/es/translation.json
- updated the spanish translation...
=> Update spanish translation.json

package.json, yarn.lock
Fix a issue with bugged shortcuts.
Related to:
https://github.com/nwutils/create-desktop-shortcuts/pull/96
=> chore: update create-desktop-shortcuts

src/locales/tr/translation.json
- Translations have been added for Nimbus options.
- Translation has been added for the download speed display option.
=> [translation ]Missing translations for Turkish have been added

src/main/events/catalogue/get-trending-games.ts, src/main/events/misc/get-badges.ts, src/main/events/user-preferences/update-user-preferences.ts, src/main/index.ts, src/main/level/sublevels/keys.ts, src/main/services/achievements/get-game-achievement-data.ts, src/main/services/python-rpc.ts
=> fix: storing rpc encrypted password

package.json, src/locales/en/translation.json, src/locales/pt-BR/translation.json, src/main/events/library/open-game-installer-path.ts, src/main/services/window-manager.ts, src/main/services/ws/events/friend-game-session.ts, src/renderer/src/components/achievements/notification/achievement-notification.tsx, src/renderer/src/declaration.d.ts, src/renderer/src/pages/settings/settings-general.tsx, src/renderer/src/pages/theme-editor/theme-editor.tsx, src/shared/index.ts, src/types/level.types.ts
- also adds option to disable friend starting game notification
=> fix: ensure achievement notification preview has same styles as actual notification [HYD-828]

src/locales/en/translation.json, src/main/events/library/change-game-playtime.ts, src/renderer/src/pages/game-details/hero/hero-panel-playtime.scss, src/renderer/src/pages/game-details/hero/hero-panel-playtime.tsx
- Added warning icon + tooltip to the game page + en translation
=> Feat: added warning to the hero-panel-playtime
